In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


In [3]:
arr2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(arr2d)

[[1 2 3]
 [4 5 6]]


In [4]:
print(arr2d[0, 1])

2


In [5]:
print(arr2d[:, 1])   # All rows, column 1
print(arr2d[0, :])   # First row
print(arr2d[0:2, 1:3])  # Submatrix

[2 5]
[1 2 3]
[[2 3]
 [5 6]]


In [7]:
print(np.sum(arr2d))           # Total sum
print(np.sum(arr2d, axis=0))   # Column-wise sum
print(np.sum(arr2d, axis=1))   # Row-wise sum

21
[5 7 9]
[ 6 15]


In [8]:
np.mean(arr2d)

np.float64(3.5)

In [9]:
print(arr2d.T)

[[1 4]
 [2 5]
 [3 6]]


In [10]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.dot(a, b))

32


In [11]:
np.random.rand(3, 3)        # Random numbers (0 to 1)
np.random.randint(1, 10, (3, 3))  # Random integers
np.random.randn(3, 3)       # Normal distribution

array([[-0.00754634,  0.05387533,  1.11377986],
       [ 0.08150705,  0.49036449,  0.59731088],
       [-0.61938944, -0.3104961 , -0.5091791 ]])

In [12]:
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

In [13]:
# Row sums
row_sums = np.sum(matrix, axis=1)
# Column sums
col_sums = np.sum(matrix, axis=0)

In [14]:
print("Matrix:\n", matrix)
print("Row sums:", row_sums)
print("Column sums:", col_sums)

Matrix:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Row sums: [ 60 150 240]
Column sums: [120 150 180]


In [15]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

In [16]:
result_manual = np.zeros((2, 2))

for i in range(2):
    for j in range(2):
        for k in range(2):
            result_manual[i][j] += A[i][k] * B[k][j]

print("Manual Multiplication:\n", result_manual)

Manual Multiplication:
 [[19. 22.]
 [43. 50.]]


In [17]:
result_numpy = np.dot(A, B)
# OR
result_numpy = A @ B

print("NumPy Multiplication:\n", result_numpy)

NumPy Multiplication:
 [[19 22]
 [43 50]]


In [18]:
# Generate dataset of 100 students with 3 subjects
dataset = np.random.randint(40, 100, (100, 3))

print("Dataset shape:", dataset.shape)
print("First 5 rows:\n", dataset[:5])

# Calculate average marks per subject
subject_mean = np.mean(dataset, axis=0)
print("Average per subject:", subject_mean)

Dataset shape: (100, 3)
First 5 rows:
 [[93 78 67]
 [51 78 46]
 [49 91 99]
 [84 62 98]
 [43 84 71]]
Average per subject: [71.52 69.02 68.59]
