# Tensors in PyTorch

In [1]:
import torch

In [6]:
scaler = torch.tensor(5)
print(scaler.shape)
print(scaler.item())

torch.Size([])
5


In [8]:
vector = torch.tensor([1,2,3])
print(vector.shape)
# print(vector.item()) # This would cause a RuntimeError for a multi-element tensor.
# If you want to access individual elements:
# print(vector[0].item())
# Or simply print the tensor itself:
print(vector)

torch.Size([3])
tensor([1, 2, 3])


In [10]:
matrix = torch.tensor([[1,2],
                       [3,4]])
print(matrix.shape)
print(matrix)

torch.Size([2, 2])
tensor([[1, 2],
        [3, 4]])


## Basic Operations

In [11]:
x = torch.tensor([1.,2.])
y = torch.tensor([3.,4.])

In [12]:
x + y

tensor([4., 6.])

In [13]:
x * y

tensor([3., 8.])

In [14]:
torch.dot(x,y)

tensor(11.)

In [15]:
A = torch.tensor([[1.,2.],
                  [3.,4.]])
B = torch.tensor([[5.,6.],
                  [7.,8.]])

In [16]:
torch.matmul(A,B)

tensor([[19., 22.],
        [43., 50.]])

In [21]:
print(tf.linalg.matmul(A, B))

tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)


## Autograd

In [24]:
x = torch.tensor(2.0, requires_grad=True)

In [25]:
y = x**2 + 3*x

In [26]:
y.backward()
print(x.grad)

tensor(7.)


# Tensors in TensorFlow

In [17]:
import tensorflow as tf

In [20]:
x = tf.constant([1.0, 2.0])
y = tf.constant([3.0, 4.0])

print(x + y)
print(x * y)
print(tf.tensordot(x, y, axes=1))

tf.Tensor([4. 6.], shape=(2,), dtype=float32)
tf.Tensor([3. 8.], shape=(2,), dtype=float32)
tf.Tensor(11.0, shape=(), dtype=float32)
